### ISSUE TITLE
openHAB3 Branch

### ISSUE THREAD

**Issue by ecdye** [mstormi/openhabian-zram#8]
We need to create an openHAB 3 branch to support minor changes to the code to ensure proper support. @mstormi could you create the branch after merging #7 and I have a PR ready to be opened when you do.

**Comment by mstormi** [comment]
branch created

**Comment by ecdye** [comment]
@mstormi I won control of zram-config. I could simply create a branch for OH2 and OH3 and make the changes there to allow for a better Open Source workflow WDYT

**Comment by mstormi** [comment]
congrats yes please do 👍

**Comment by ecdye** [comment]
Will do, I will create a branch for OH2 and one for OH3 then create their respective PR's in openhabian.
